logging:
  level:
    org.springframework.security: INFO
    org.hibernate: ERROR
    org.springframework.transaction.interceptor : TRACE

spring:
      datasource:
          url : jdbc:h2:mem:testdb
          driverClassName : org.h2.Driver
          username : sa
          password :
          hikari:
            connectionTimeout : 20000
            maximumPoolSize: 5
            poolName : HikariPoolZZZ
      jpa:
        database-platform : org.hibernate.dialect.H2Dialect
        properties:
               hibernate:
                   show_sql : true
      h2:
        console :
              enabled : true
app:
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: bXktc2VjcmV0LWtleS13aGljaC1zaG91bGQtYmUtY2hhbmdlZC1pbi1wcm9kdWN0aW9uLWFuZC1iZS1iYXNlNjQtZW5jb2RlZAo=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000